httpserver:
  host:
  port: 8888
memory:
  dsn:
  maxConnectAttempts:
postgres:
  dsn: postgres://user:password@postgres:5432/creator
  maxConnectAttempts: 5
mysql:
  dsn: user:password@tcp(10.5.0.7:3306)/creator
  maxConnectAttempts: 5
mongodb:
  dsn: mongodb://root:password@10.5.0.8:27017
  maxConnectAttempts: 5
clickhouse:
  dsn: 10.5.0.10:9000
  maxConnectAttempts: 5
tarantool:
  dsn: 10.5.0.11:3301
  maxConnectAttempts: 5
aerospike:
  host: 10.5.0.12
  port: 3000
  maxConnectAttempts: 5